# Generated by Django 5.0.6 on 2024-06-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='payment_type',
            field=models.CharField(choices=[('kirim', 'input'), ('chiqim', 'output')], max_length=8),
        ),
    ]
