# Generated by Django 5.0.6 on 2024-06-09 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0002_alter_account_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='payment_type',
            field=models.CharField(choices=[('kirim', 'Input'), ('chiqim', 'Output')], max_length=8),
        ),
    ]
