# Generated by Django 5.0.6 on 2024-06-10 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0005_rename_is_authenticated_user_isauthenticated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='isauthenticated',
        ),
        migrations.AddField(
            model_name='user',
            name='iauthenticated',
            field=models.BooleanField(default=False),
        ),
    ]
