# Generated by Django 5.0.6 on 2024-06-10 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0006_remove_user_isauthenticated_user_iauthenticated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='iauthenticated',
        ),
    ]
